version: '3'

services:
  neologism:
    container_name: neologism_nginx_front_server
    ports:
      - '3000:3000'
      - '80:80'
    environment:
      ROOT_URL: ${ROOT_URL:-http://cloud33.dbis.rwth-aachen.de}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000  
  
  mongo:
    container_name: neologism_db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

#   recommender:
#     container_name: neologism_recommender
#     image: registry.git.rwth-aachen.de/neologism/recommender:latest
#     ports:
#       - '8080:8080'
