version: '3'

services:
  neologism:
    image: registry.git.rwth-aachen.de/neologism/neologism2:latest
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  recommender:
    image: registry.git.rwth-aachen.de/neologism/recommender:latest
    ports:
      - '8080:8080'

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
