version: '3'

services:
  neologism:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        METEOR_CLIENT_CONN_URL: ${METEOR_CLIENT_CONN_URL:-http://localhost/api}
    ports:
      - '3000:3000'
      - '80:80'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
      
  recommender:
    image: registry.git.rwth-aachen.de/neologism/recommender:latest
    ports:
      - '8080:8080'

volumes:
  data:
