image: docker:19.03
services:
  - docker:dind

stages:
  - push

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

docker_build_and_push:
  image: docker:19.03
  stage: push
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - envsubst < app/src/assets/env.template.js > app/src/assets/env.js
    - docker build --build-arg METEOR_CLIENT_CONN_URL=$CLIENT_CONN_URL -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $LATEST_TAG
  only:
    - main
