version: '3'

services:
  
  neologism:
    container_name: neologism_app
    ports:
      - '3000:3000'
      - '80:80'

  recommender:
    container_name: neologism_recommender
    ports:
      - '8080:8080'
