version: '3'

services:

  neologism:
    container_name: neologism_app
    image: ghcr.io/semantic-society/neologism/neologism2:latest
    # build creates a local docker container, to use the image comment it out
    build:
      context: .
      dockerfile: Dockerfile
      
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${ROOT_URL:-http://localhost:4200}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000
      METEOR_SETTINGS: '{ "storageLocation":"/etc/neologism/uploads/vocabularies" }'
      NEO_GUSER:
      NEO_GPASS:
  mongo:
    container_name: neologism_db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'

  recommender:
    container_name: neologism_recommender
    image: registry.git.rwth-aachen.de/neologism/recommender:latest

volumes:
  data:
  uploads:
