version: '3'

services:

  neologism:
    container_name: neologism_app
    image: ghcr.io/semantic-society/neologism/neologism2:latest
    # build creates a local docker container, to use the image comment it out
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #  args:
    #    # This is variable is use to configure meteor-client bundle 
    #    METEOR_CLIENT_CONN_URL: http://localhost/api      
    depends_on:
      - mongo
    volumes:
      - data:/data/uploads
    environment:
      ROOT_URL: http://localhost
      MONGO_URL: mongodb://mongo:27017/neologism
      MONGO_HOST_PORT: mongo:27017
      CROOT_URL: ${CROOT_URL:-http://localhost:3000}
      CDDP_URL: ${CDDP_URL:-http://localhost:3000}
      PORT: 3000
      METEOR_SETTINGS: '{ "storageLocation":"/data/uploads/vocabularies","forbidClientAccountCreation" :"true" }'
      HTTP_FORWARDED_COUNT: 1

  mongo:
    container_name: neologism_db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'

  recommender:
    container_name: neologism_recommender
    image: ghcr.io/semantic-society/recommender/recommender:latest

volumes:
  data:
