version: '3'

services:
  
  neologism:
    container_name: neologism_app
    image: registry.git.rwth-aachen.de/neologism/neologism2:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This is variable is use to configure meteor-client bundle 
        METEOR_CLIENT_CONN_URL: ${METEOR_CLIENT_CONN_URL:-http://localhost:3000}
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      METEOR_SETTINGS: '{ "storageLocation":"/etc/neologism/uploads/vocabularies" }' 
  
  mongo:
    container_name: neologism_db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger

#   recommender:
#     container_name: neologism_recommender
#     image: registry.git.rwth-aachen.de/neologism/recommender:latest

volumes:
  data:
  uploads:
