version: '3'

services:
  
  neologism:
    container_name: neologism_app
    ports:
      - '3000:3000'
      - '4200:80'
      - '3001:3001'
    volumes: 
      - uploads:/etc/neologism/uploads/vocabularies
  
  mongo:
    container_name: neologism_db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

  recommender:
    container_name: neologism_recommender
    image: registry.git.rwth-aachen.de/neologism/recommender:latest
    ports:
     - '8080:8080'
