version: '3'

services:

  neologism:
    container_name: neologism_app
    image: ghcr.io/semantic-society/neologism/neologism2:latest
    # build creates a local docker container, to use the image comment it out
    build:
     context: .
     dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - data:/data/uploads
    environment:
      
      # Required for meteor server startup
      # https://docs.meteor.com/v2.2/environment-variables.html
      PORT: 3000
      MONGO_URL: mongodb://mongo:27017/meteor
      METEOR_SETTINGS: '{ "storageLocation":"/data/uploads/vocabularies","forbidClientAccountCreation" :"false" }'
      HTTP_FORWARDED_COUNT: 1
      ROOT_URL: ${ROOT_URL:-http://localhost/api}
      
      # Required for meteor client-side bundle 
      # used as external in angular static bundle 
      METEOR_CLIENT_CONFIG_URL: ${METEOR_CLIENT_CONFIG_URL:-http://localhost/api}

      

  mongo:
    container_name: neologism_db
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'

  recommender:
    container_name: neologism_recommender
    image: ghcr.io/semantic-society/recommender/recommender:latest

volumes:
  data:
