name: ci
on:
  push:
    branches:
      - 'main'
      - '166-move-ci-pipeline'
jobs:
  build-and-push:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/neologism2:${{ github.sha }}
            docker.pkg.github.com/${{ github.repository }}/neologism2:${{ github.ref }}
            docker.pkg.github.com/${{ github.repository }}/neologism2:latest
